### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by Abhinav-3359**

### CODE REVIEW

**Comment by AnshSinghSonkhia** [comment]
Send the video and screenshots of the working.

**Comment by Abhinav-3359** [comment]
msap1
msap2

**Comment by Abhinav-3359** [comment]
sir these 2 screenshot shows the working

**Comment by AnshSinghSonkhia** [comment]
Yeah! it's working.
But, Sorry @Abhinav-3359 ji, this is changing the style of my website.

**Comment by Abhinav-3359** [comment]
What if I add this in the footer ?

**Pull request closed without merging**
