### PR TITLE
feat: song duration with reverse timer

### PR DESCRIPTION
**Pull request by Shubhcs01**
Added timer in music player tells how much time left.

ISSUE SOLVED #17 

Demo -> https://drive.google.com/file/d/19ZVBhiBdqEJb5Kk0v_qCnteactdGEASp/view?usp=sharing

### CODE REVIEW

**Comment by Shubhcs01** [comment]
@AnshSinghSonkhia Merge conflict resolved. Please review it.

**Comment by AnshSinghSonkhia** [comment]
Hey @Shubhcs01,
Kindly comment some screenshots and videos of the working...

**Comment by Shubhcs01** [comment]
> Hey @Shubhcs01, Kindly comment some screenshots and videos of the working...

Already commented the video drive link above.

here again -> [working Demo]  (https://drive.google.com/file/d/19ZVBhiBdqEJb5Kk0v_qCnteactdGEASp/view?usp=sharing)

**Comment by Shubhcs01** [comment]
@AnshSinghSonkhia please review it 🙂

**Pull request closed without merging**
